/*
  Warnings:

  - The values [HRGA_GROUP_LEADER] on the enum `Position` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "public"."Position_new" AS ENUM ('PROD_ENG_SPV', 'PRODUCTION_GROUP_LEADER', 'MOCO_LEADER', 'CCR_ADMIN', 'DRIVER_DOUBLE_TRAILER', 'WEIGHT_BRIDGE_ADMIN', 'SIDE_DUMP_SPOTTER', 'PLAN_SPV', 'LOGISTIC_SPV', 'PLANNER', 'PLANT_GROUP_LEADER', 'TYRE_GROUP_LEADER', 'LOGISTIC_GROUP_LEADER', 'MECHANIC_JR', 'MECHANIC_SR', 'WELDER', 'ELECTRICIAN', 'TYREMAN', 'FABRICATION', 'OPERATOR_FUEL_TRUCK', 'PLANT_ADMIN', 'TYRE_ADMIN', 'LOGISTIC_ADMIN', 'HSE_SPV', 'SAFETY_OFFICER', 'ENVIRONMENT_OFFICER', 'PARAMEDIC', 'HSE_ADMIN', 'HR_GROUP_LEADER', 'GA_GROUP_LEADER', 'PDCA_OFFICER', 'PURCHASING_SPV', 'IT_SUPPORT', 'DOCTOR', 'DEPT_HEAD_PRODUCTION_ENGINEERING', 'HRGA_SPV', 'MECHANIC_INSTRUCTOR', 'DEPT_HEAD_PLANT_LOGISTIC', 'OPERATOR_WATER_TRUCK', 'OPERATOR_CRANE_TRUCK', 'HRGA_ADMIN', 'CAMP_SERVICE_TECHNICIAN', 'CAMP_SERVICE_HELPER', 'DEPT_HEAD_HRGA', 'TRAINER_MECHANIC', 'TRAINER_DOUBLE_TRAILER', 'GA_INFRASTRUCTURE', 'TOOLKEEPER', 'MECHANIC_MAGANG', 'HRGA_OFFICER', 'DRIVER_SARANA', 'DRIVER_LV');
ALTER TABLE "public"."RecruitmentForm" ALTER COLUMN "appliedPosition" TYPE "public"."Position_new" USING ("appliedPosition"::text::"public"."Position_new");
ALTER TABLE "public"."HiredEmployee" ALTER COLUMN "hiredPosition" TYPE "public"."Position_new" USING ("hiredPosition"::text::"public"."Position_new");
ALTER TYPE "public"."Position" RENAME TO "Position_old";
ALTER TYPE "public"."Position_new" RENAME TO "Position";
DROP TYPE "public"."Position_old";
COMMIT;
